/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_editor_NativeBridge */

#ifndef _Included_com_editor_NativeBridge
#define _Included_com_editor_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_editor_NativeBridge
 * Method:    createBuffer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_editor_NativeBridge_createBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_editor_NativeBridge
 * Method:    destroyBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_editor_NativeBridge_destroyBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_editor_NativeBridge
 * Method:    loadFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_editor_NativeBridge_loadFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_editor_NativeBridge
 * Method:    saveFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_editor_NativeBridge_saveFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_editor_NativeBridge
 * Method:    getLineCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_editor_NativeBridge_getLineCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_editor_NativeBridge
 * Method:    findByteInLine
 * Signature: (JIB)J
 */
JNIEXPORT jlong JNICALL Java_com_editor_NativeBridge_findByteInLine
  (JNIEnv *, jclass, jlong, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
